version: "3.9"
services:
  spark-app:
    build: .
    container_name: spark_csv_to_avro
    volumes:
      - ./data:/app/data
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
    command: ["java", "--add-opens=java.base/jdk.internal.platform=ALL-UNNAMED", "-XX:-UseContainerSupport", "-Dspark.executor.processTreeMetrics.enabled=false", "-Dspark.metrics.conf.*.sink.jmx.class=org.apache.spark.metrics.sink.NullSink", "-jar", "/app/app.jar"]

  spark-test:
    build:
      context: .
      target: builder
    container_name: spark_csv_test
    command: ["sbt", "test"]