services:
  spark-app:
    build: .
    container_name: spark_csv_to_avro
    volumes:
      - ./data:/app/data
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
    command: [
      "java",
      "-XX:-UseContainerSupport",  # ⬅️ **Critical fix for the NullPointerException**
      "--add-opens=java.base/jdk.internal.platform=ALL-UNNAMED", # ⬅️ For reflective access warnings
      "--add-opens=java.base/java.nio=ALL-UNNAMED",             # ⬅️ For reflective access warnings
      "-Dlog4j.configurationFile=/app/log4j2.properties",
      "-jar",
      "/app/app.jar"
    ]
  spark-test:
    build:
      context: .
      target: builder
    container_name: spark_csv_test
    command: ["sbt", "test"]