services:
  spark-app:
    build: .
    container_name: spark_csv_to_avro
    volumes:
      - ./data:/app/data:delegated
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
    command: [
      "/opt/spark/bin/spark-submit",
      "--class", "com.example.CsvToAvroApp",
      # "--driver-java-options", "-Dlog4j.configurationFile=/app/log4j2.properties -Dlog4j.debug=true",
      "/app/app.jar"
    ]
  spark-test:
    build:
      context: .
      target: builder
    container_name: spark_csv_test
    command: ["sbt", "test"]