services:
  spark-app:
    build: .
    container_name: spark_csv_to_avro
    volumes:
      - ./data:/app/data
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
    command: [
      "spark-submit",
      "--packages", "org.apache.spark:spark-sql_2.12:3.5.0",
      "--class", "com.example.CsvToAvroApp",
      "/app/app.jar"
    ]
  spark-test:
    build:
      context: .
      target: builder
    container_name: spark_csv_test
    command: ["sbt", "test"]