services:
  spark-app:
    build: .
    container_name: spark_csv_to_avro
    volumes:
      - ./data:/app/data
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
      - JAVA_OPTS=-Dlog4j.configurationFile=/app/log4j2.properties --add-opens=java.base/jdk.internal.platform=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED -XX:-UseContainerSupport -Dspark.executor.processTreeMetrics.enabled=false
    command: ["java", "-jar", "/app/app.jar"]

  spark-test:
    build:
      context: .
      target: builder
    container_name: spark_csv_test
    command: ["sbt", "test"]